### ISSUE TITLE
Cannot requests with code response codes, e.g. CHANGED

### ISSUE THREAD

**Issue by therealprof** [chrysn/aiocoap#122]
In order to implement the separate replies feature I need to be able to create requests which have essential codes which are considered to be response codes and currently prevented from being used.

As mentioned in #116, there's this concept in CoAP which allows to send replies in separate packets rather than piggyback which requires to acknowledge the reception of the request (to prevent the server from resending CONs) and then create a new CON with a "response" code. When trying to do that `aiocoap` throws an `AssertionError`:
```
Traceback (most recent call last):
 ...
  File "/Users/egger/OSS/aiocoap/aiocoap/protocol.py", line 726, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/Users/egger/OSS/aiocoap/aiocoap/protocol.py", line 778, in _run
    blockresponse = await blockrequest.response
  File "/Users/egger/OSS/aiocoap/aiocoap/protocol.py", line 306, in send
    request_interface.request(plumbing_request)
  File "/Users/egger/OSS/aiocoap/aiocoap/tokenmanager.py", line 175, in request
    assert msg.code.is_request(), "Message code is not valid for request"
AssertionError: Message code is not valid for request
```

**Comment by chrysn** [comment]
That's by design. aiocoap is an abstraction over the CoAP protocol, and won't be abetting protocol abuse.

Judging from #116, what you actually want to do is to send a delayed response (our messages crossed over there) to the given request; aiocoap (at least outside the library internals, which you're free to access but that's probably not what you want) won't let you send a response to a request in any other way than as the response to the request handler.
