### ISSUE TITLE
"render_METHOD" method names violate PEP8 naming conventions

### ISSUE THREAD

**Issue by aellwein** [chrysn/aiocoap#14]
"render_METHOD" method names violate PEP8 naming conventions.
may be it is better to use lowercase names, "get", "post", "put", "delete" etc. ?

**Comment by chrysn** [comment]
that naming stems from the original txthings, which seems to implement some more generic twisted interface. one could argue that the METHOD verbs of both HTTP and CoAP are always uppercased, which forms a prevailing style, but on the other hand we don't have to care much about compatibility yet (no api-stable release has been made, my concern is mainly about doing changes in a way that allows library users to easily migrate, eg. with search/replace).

i'm willing to do that change, but would also accept a pull request; thanks for reporting.

**Comment by aellwein** [comment]
No problem. [Here](https://github.com/chrysn/aiocoap/pull/18) is the pull request.

**Comment by chrysn** [comment]
cherry-picked and done, thank you.

i've changed two minor things:

* commit messages should have a short single-line description followed by an empty line. (i don't strictly follow the [50 chars limit](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), but the general formatting has good reasons.
* use str(x) instead of x.__str__(), avoiding python internals

**Comment by aellwein** [comment]
Sounds reasonable, thank you!
