### ISSUE TITLE
Multicast Interface

### ISSUE THREAD

**Issue by ackermann-michael-ext-siemens** [chrysn/aiocoap#140]
When sending multicast messages (on Linux, using `udp6.py` as transport), I only see messages being sent when I set the `IPV6_MULTICAST_HOPS` and `IPPROTO_IPV6` options on the socket used internally by aiocoap:
```python
sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_MULTICAST_HOPS, 128)
sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_MULTICAST_IF, interface_index)
```

Is there a better send multicast messages?
E.g. by configuring the `context` to enable it to send multicast messages?

**Comment by chrysn** [comment]
Just to make sure I'm on the right side when reproducing: Are you sending from a bound (sever; if: to wild-card or a particular interface) or unbound (client) socket?

Are, on the interface you are monitoring, there members of the group on the interface? (AFAICT if the Linux box is behaving as a router, it might monitor group memberships on the interface). Are you sending to a link-local or site-local address?

**Comment by ackermann-michael-ext-siemens** [comment]
I am using a client socket to send to the realm-local all-coap nodes address (`ff03::fd`).

An MWE (which horrendously hackily extracts the socket used by aiocoap), which allows me to send multicast packets on the Ethernet (`eno1`) interface:

```python
import logging
import asyncio
import socket

from aiocoap import *

logging.basicConfig(level=logging.INFO)

async def main():
    protocol = await Context.create_client_context()
    sock = protocol.request_interfaces[2].token_interface.message_interface.transport._RecvmsgSelectorDatagramTransport__sock # Oh lawd
    # sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_MULTICAST_HOPS, 128)
    interface_index = socket.if_nametoindex('eno1')
    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_MULTICAST_IF, interface_index)
    
    request = Message(code=GET, uri='coap://[ff03::fd]/.well-known/core')

    try:
        response = await protocol.request(request).response
    except Exception as e:
        print('Failed to fetch resource:')
        print(e)
    else:
        print('Result: %s\n%r'%(response.code, response.payload))

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

It seems my initial analysis was imprecise: 
 - setting `IPV6_MULTICAST_HOPS` is not necessary for multicasts to work
 - even without setting `IPV6_MULTICAST_IF`, a multicast package is sent. Since I am connected to two networks (Wifi and Ethernet), and was only monitoring Ethernet, I missed the packet going out on Wifi.

Maybe a better way to put my original question: How do I tell aiocoap which network interface it should send multicast packets on if there are multiple?

Regarding if there are members of the group on the interface: 
I am not sure I understand completely: What kind of members are you referring to?

**Comment by HRogge** [comment]
I would like to raise this question too... the "udp6" transport supports setting the outgoing multicast interface via pktinfo, but I don't see a good way to set it from the app.

if I create a message the following way, how do I set the outgoing interface?
```
request = Message(code=POST, payload=my_payload, uri="coap://224.0.1.187/path")

response = await self.protocol.request(request).response
```

**Comment by HRogge** [comment]
I did some more testing and got some "funny" results... I use a few bash scripts to setup two network namespaces, connected with a veth. This way I can run two instances of aiocoap (server and client) and they only see the dedicated network connection between them, no interaction with the rest of the system (including routing tables).
(I can upload the scripts if someone is interested looking at them)

Aiocoap client cannot join the IPv4 multicast group unless there is a default route present in the system. I guess a UNICAST route for 224.0.1.187 would also be okay, but I have to check.

Even when I get the multicast transmissionactive (I can see the IPv4 packet arriving in the server namespace), the server does not see the incoming multicast.

What I can see is that the call `await loop.getaddrinfo(...)` in udp6.py line 252 tries to bind the socket to the loopback address (::1), which doesn't sound right.

I cannot use the "bind" parameter to bind the socket to the correct IP, because this prevents the socket from receiving multicast at all.

**Comment by HRogge** [comment]
Fun fact... if you try to only set the port of the server, but not the IP ( `bind=(None, 1234)` ) the default to '::' for the IP doesn't work. Maybe line 244 in udp6.py should be:

`        bind = (bind[0] or '::', bind[1] or COAP_PORT)`

**Comment by HRogge** [comment]
Good news... the current code works well for IPv6... no need for any change or a default route. Both linklocal and sitelocal multicast works well.

Bad news... ipv4 multicast is broken. Both server and client side.

**Comment by HRogge** [comment]
According to my tests the following steps can fix the IPv4 multicast problem.

For the server I had to bind the socket with IP_ADD_MEMBERSHIP (see udp6.py _create_transport_endpoint() ) to the real interface IP (not 0.0.0.0). This (as far as I know, still have to test) can also be done for multiple interfaces on the same socket.

For the client I had to set the outgoing multicast interface with IP_MULTICAST_IF:
`sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton('<interface-ip'))`
I also think this can be done for multiple interfaces on the same socket.

Still, in both cases the server/client needs to be aware which interfaces are used and has to learn the interface IP address.

**Comment by HRogge** [comment]
Another useful fact...

you CAN select the outgoing interface for an IPv4 multicast by using IPV6_PKTINFO (example sends to interface index 17):
```
message.remote.pktinfo = struct.pack(
                    '16sI',
                    socket.inet_pton(socket.AF_INET6, '::ffff:0.0.0.0'),
                    17)
```

**Comment by HRogge** [comment]
I think I have a solution for the problem... I did a couple of tests with a set of scripts that use network-namespaces to allow me to run three isolated COAP server clients, with a veth-pipe between each. This way it is possible to develop Multicast code in a Multi-Interface environment without side effect from the development network setup.

The new code allows to select a list of "incoming" network interfaces for multicast... it can configure the outgoing multicast interface for both IPv4 and all IPv6 remote destinations by using the % operator  (similar to linklocal IPv6 multicast)... and it allows to select the source IP without binding the socket to the IP (which would make receiving multicast impossible).

The combination should allow both sending and receiving IPv4 and IPv6 multicast with a single socket.

See 3a6af58421cb67fddc5bcf854e5faab28b3497e1 and the commit before this. I Can send you a pull request (combined or without with the 1-second timeout for sending no-response messages).

**Comment by HRogge** [comment]
I have sent you pull request #191 to fix the multicast related issues I found above, please consider merging it. If there is a problem with the pull request, please tell me.

**Comment by chrysn** [comment]
> I have sent you pull request #191 to fix the multicast related issues
> I found above, please consider merging it. If there is a problem with
> the pull request, please tell me.

Sorry, I was still caught up in trouble with the CI which made it hard
to evaluate PRs; looking it through.

**Comment by chrysn** [comment]
I've done some evaluation of how sending to multicast addresses on a given interface behaves on Linux (full tool [in the working branch](https://github.com/chrysn/aiocoap/blob/multicast-fixes/contrib/multicast-platform-evaluation), when this link breaks there should be an equivalent file in the master branch instead) -- to me it appears like a bug in the operating system (given things work much more smoothly on FreeBSD), but I'll be hashing that out with kernel folks.

The practical consequence I'd draw from this is that while it still makes sense to use zone identifiers in destination addresses, and that they can be supplied in the usual half-legal URI form `coap://[ff05::db8:1%eth0]` when necessary (whereas global or ULA multicast addresses don't need that trick). Then, it'll just be a matter of working around. Possibly, the multicast address doesn't neven need to be recognized -- if that works (and I'm about to try), zone identifiers would just *always* be put in the sender address (which is created empty as @HRogge showed in #191) instead of the destination (which might be needless when sending to fe80 addresses, but I'd like to keep complexity low).

From your applications of multicast, do you expect any trouble if local addresses are always given as `ff0x::...%ifname`? (This is, so far, only considering the client side; server side is next but first I need a working client to test with ;-) )

**Comment by chrysn** [comment]
After some evaluation, IRC consultation and almost writing to LKML I found an innocuous line in [ipv6(7)](https://linux.die.net/man/7/ipv6):

> sin6_scope_id is an ID depending on the scope of the address. [...] Linux only supports it for link-local addresses, in that case sin6_scope_id contains the interface index [...].

Faithful to the letter of that sentence, things work for ff02:: link-local multicast, but not for ff05:: site-local.

Further testing (so far, only with pings) indicates that even for the link-local cases, setting (unspecified IP address, zone ID) as the package source is just as good for picking the interface as is setting the zone ID as the outgoing scope identifier. Thus, my plan of action for fixing this is not to carry around an additional interface identifier, but to use the % style consistently in local URIs, and just pack the information into the local rather than the remote address.

This might make workarounds look weird (eg. it seems that on Linux you have to set an interface identifier even when using unicast-prefix based addresses, so that a request would go to `coap://[ff35:30:2001:db8::1%eth0]` whereas that's not necessary to specify on FreeBSD), but should largely give a consistent appearance and API.

**Comment by HRogge** [comment]
Yes, link-scope is only defined for linklocal IPs in IPv6... everything else is non-standard.
That is why I used pktinfo for sending out datagrams on a specific interface without using multiple sockets.

The reason why I also store the "local" endpoint is that you sometimes need to know from which interface you received a multicast.

**Comment by chrysn** [comment]
Thanks, I was unaware that this is not only a Linux thing but not specified otherwise. (Although that still does not make a lot of sense to me; why couldn't the sockaddr have an identifier of any level, be it a link or a site identifier?)

The local endpoints would still be available as the `.remote.pktinfo` (should really have been `.endpoint` rather than `.remote`) as it already is now, full with interface identifier if present.

**Comment by chrysn** [comment]
@HRogge, would the interface introduced in [fa2425ab](https://gitlab.com/aiocoap/aiocoap/-/commit/fa2425aba422207faaf1d3d13c2175b2f431f3b7) work for the cases where you need the interface?
