### ISSUE TITLE
how can I log the incoming message's detail

### ISSUE THREAD

**Issue by scarleast** [chrysn/aiocoap#143]
I want to run a coap server, and print the detail(like source ip,port,request path),how can I do that?

**Comment by chrysn** [comment]
The easiest way is probably to subclass Site to call out into an additional logging function, roughly like this:

```python
class PrintingLogSite(aiocoap.resources.Site):
    def render(self, request):
        print("Request from {} to {}".format(request.remote, request.opt.uri_path))
        return super().render(request)
```

Two notes here:
* aiocoap already does some logging -- it's not particularly targeted at logging the path, but it might give you enough information depending on what you need to log for. It can be enabled / redirected via the Python logging module; aiocoap servers by default log to a logger named 'coap-server'. (The server.py example, for example, shows all log output).
* The request's remote is an object that encodes a bit more information about the requester than just the IP address and port, for example the protocol used (whether it's UDP or TCP) or the security context. Expect anything in there that implements the EndpointAddress interface; if you want to implement source based controls (which I would not recommend), check for whether the remote is of a particular type (eg. a UDP6EndpointAddress), reject otherwise, and carefully read new aiocoap versions' change logs as the properties of those objects might still change.

**Comment by scarleast** [comment]
thanks a lot！
