### ISSUE TITLE
fileserver doesn't bind to ipv6 address

### ISSUE THREAD

**Issue by david-drinn** [chrysn/aiocoap#164]
I'm trying to get the `aiocoap-fileserver` I'm running to be accesible from outside my machine over ipv6. 

In that effort, I tried to bind directly to my ethernet port's ipv6. But I get an exception saying it's an invalid argument. I'm a little lost.

```
$ ./contrib/aiocoap-fileserver -vvv --bind '[fe80::ca60:ff:fea0:9888]' stash 
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1051, in create_server
    sock.bind(sa)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./contrib/aiocoap-fileserver", line 206, in <module>
    FileServerProgram.sync_main()
  File "/home/me/.local/share/virtualenvs/aiocoap/lib/python3.6/site-packages/aiocoap/util/cli.py", line 67, in sync_main
    loop.run_until_complete(main.initializing)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "./contrib/aiocoap-fileserver", line 164, in start
    await self.start_with_options(**vars(opts), server_opts=server_opts)
  File "./contrib/aiocoap-fileserver", line 184, in start_with_options
    self.context = await server_context_from_arguments(server, server_opts)
  File "/home/me/.local/share/virtualenvs/aiocoap/lib/python3.6/site-packages/aiocoap/cli/common.py", line 98, in server_context_from_arguments
    return await Context.create_server_context(site, namespace.bind, _ssl_context=ssl_context, **kwargs)
  File "/home/me/.local/share/virtualenvs/aiocoap/lib/python3.6/site-packages/aiocoap/protocol.py", line 244, in create_server_context
    lambda tman: TCPServer.create_server(bind, tman, self.log, loop))
  File "/home/me/.local/share/virtualenvs/aiocoap/lib/python3.6/site-packages/aiocoap/protocol.py", line 156, in _append_tokenmanaged_transport
    transport = await token_interface_constructor(tman)
  File "/home/me/.local/share/virtualenvs/aiocoap/lib/python3.6/site-packages/aiocoap/transports/tcp.py", line 380, in create_server
    ssl=_server_context)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1055, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 22] error while attempting to bind on address ('fe80::ca60:ff:fea0:9888', 5683, 0, 0): invalid argument
```

**Comment by chrysn** [comment]
(This response is two-parted as I just found out while testing that there's an aiocoap bug in there as well):

When you're using link-local IPv6 addresses (`fe80::/7`), you have to specify a zone identifier with the address. (That's not a constraint of aiocoap but of IPv6 in general, but in return this allows having link-local addresses *and* multiple network interfaces on a single host in the first place).

If your ethernet interface is called `eth0`, your command should be `./contrib/aiocoap-fileserver -vvv --bind '[fe80::ca60:ff:fea0:9888%eth0]' stash`.

---

Except, it doesn't, because while `bind` does do some things that `getaddrinfo` usually does, it doesn't do all of them. (It does resolve names, but it won't fill in a zone identifier). That is a bug in aiocoap, which is to be fixed by adding a resolution step.

Until I've fixed, are you sure you need to bind to the link-local address? (From the way you introduced your setup it sounds a bit like the default behavior would do, but you may need to fill in the client's used network interface name in its request, a la `aiocoap-client 'coap://[fe80::ca60:ff:fea0:9888%eth0]/`).

**Comment by david-drinn** [comment]
Ah, ok, that makes sense. That's similar to `ping6` behavior. Yes, I'm very green at ipv6.

No, I'm not sure I need to bind to the link-local address. I think the default behavior is to link to `[::]` which I think should do what I need (access the coap server from another machine on my network), but I was just trying different things while troubleshooting.

**Comment by david-drinn** [comment]
> but you may need to fill in the client's used network interface name in its request, a la aiocoap-client 'coap://[fe80::ca60:ff:fea0:9888%eth0]/)

Yes, I believe that did the trick. Thanks for your assistance for my dumb ipv6 issue.

**Comment by david-drinn** [comment]
> Except, it doesn't, because while bind does do some things that getaddrinfo usually does, it doesn't do all of them. (It does resolve names, but it won't fill in a zone identifier). That is a bug in aiocoap, which is to be fixed by adding a resolution step.

Shall I open another issue for that, or leave this one for it?

**Comment by chrysn** [comment]
On Wed, Jun 05, 2019 at 02:19:00PM -0700, David Drinnan wrote:
> Shall I open another issue for that, or leave this one for it?

No, I'll track that here (feel free to unsubscribe from this issue if
you want); the subject and problem description do describe an aiocoap
bug.
