### ISSUE TITLE
Multicast requests to ff02::1 behave different than those to ff02::fd

### ISSUE THREAD

**Issue by chrysn** [chrysn/aiocoap#171]
Current tests are only executed on ff02::1 (all nodes) and should be extended to ff02::fd (all CoAP nodes) where I've seen practical tests fail.

**Comment by HRogge** [comment]
The problem is typically that the multicast address is not registered with the socket/interface. "all nodes" is always registered, so it doesn't fit the testcase well.

Same problem with 224.0.0.1 (all node IPv4 multicast).

You can see the effect by running "ip maddress", it shows which multicast addresses are currently registered to an interface.

**Comment by chrysn** [comment]
That's a good point, thanks -- there is an explicit joining step on server creation, but if that silently fails, that would explain some behavior.

**Comment by HRogge** [comment]
Can you give me a pointer where it happens in the code?

**Comment by chrysn** [comment]
https://github.com/chrysn/aiocoap/blob/9b249a22cb3b7316dfa7ebb32bafd2dc873df61a/aiocoap/transports/udp6.py#L216

**Comment by HRogge** [comment]
I think for sending linklocal ipv6 multicast you will need to set at least the multicast interface with IPV6_MULTICAST_IF.
