### ISSUE TITLE
RAM leakage problem with receiving PUT messages

### ISSUE THREAD

**Issue by bzasadny** [chrysn/aiocoap#182]
Hi,
I've noticed a problem with RAM memory leakage on server side after migration from 0.3 to 0.41b.
Memory is not deallocated when client is deactivated.
I have the same situation with example code from https://aiocoap.readthedocs.io/en/latest/examples.html with small modification on client side:

```python
import logging	
import asyncio	
import time	
from aiocoap import *	
logging.basicConfig(level=logging.INFO)	
async def main():	
    """Perform a single PUT request to localhost on the default port, URI	
    "/other/block". The request is sent 2 seconds after initialization.	
    The payload is bigger than 1kB, and thus sent as several blocks."""	
    context = await Context.create_client_context()	
    await asyncio.sleep(2)	
    while True:	
        payload = b"The quick brown fox jumps over the lazy dog.\n" * 30	
        request = Message(code=PUT, payload=payload, uri="coap://localhost/other/block")	
        response = await context.request(request).response	
        print('Result: %s\n%r'%(response.code, response.payload))	
        time.sleep(0.1)	
if __name__ == "__main__":	
    asyncio.get_event_loop().run_until_complete(main())
```

To debugging memory leakage I've used https://pypi.org/project/memory-profiler/
Simple screen from my tests:
![image](https://user-images.githubusercontent.com/10357933/73954706-7e8aa880-4902-11ea-8839-38aacfc203c0.png)

Bellow damp from memory:
```
4480	<class ‘dict’> {(b’\x1a\xba’, <_Address via <aiocoap.transports.simplesocketserver._DatagramServerSocketSimple obje
2241	<class ‘set’> {<weakref at 0x10a833bf0; to ‘_asyncio.Task’ at 0x10aa40050>, <weakref at 0x10a72a950; to ’_asyncio.
1463	<class ‘dict’> {‘__name__‘: ‘lib’, ‘__doc__‘: None, ‘__package__‘: None, ‘__loader__‘: None, ‘__spec__‘: None, ’_or
1457	<class ‘dict’> {‘CRYPTOGRAPHY_PACKAGE_VERSION’: <cdata ‘char *’ 0x109f2f8bc>, ‘Cryptography_HAS_EC2M’: 1, ’Cryptogr
1298	<class ‘dict’> {4441733808: <weakref at 0x108ced770; to ‘type’ at 0x108bf7ab0 (type)>, 4441762480: <weakref at 0x10
314	<class ‘dict’> {‘sys’: <module ‘sys’ (built-in)>, ‘builtins’: <module ‘builtins’ (built-in)>, ‘_frozen_importlib’: 
290	<class ‘dict’> {‘__name__‘: ‘os’, ’__doc__‘: “OS routines for NT or Posix depending on what system we’re on.\n\nThi
262	<class ‘list’> [‘altsep’, ‘curdir’, ‘pardir’, ‘sep’, ‘pathsep’, ‘linesep’, ‘defpath’, ‘name’, ‘path’, ‘devnull’, ’S
256	<class ‘list’> [‘<0>’, ‘POP_TOP’, ‘ROT_TWO’, ‘ROT_THREE’, ‘DUP_TOP’, ‘DUP_TOP_TWO’, ‘<6>‘, ‘<7>‘, ‘<8>’, ‘NOP’, ’UN
256	<class ‘list’> [‘=00’, ‘=01’, ‘=02’, ‘=03’, ‘=04’, ‘=05’, ‘=06’, ‘=07’, ‘=08’, ‘=09’, ‘=0A’, ‘=0B’, ‘=0C’, ‘=0D’, '
bytes:
131304	 {<weakref at 0x10a833bf0; to ‘_asyncio.Task’ at 0x10aa40050>, <weakref at 0x10a72a950; to ‘_asyncio.
131256	 <_io.BufferedReader name=‘<stdin>‘>
131256	 <_io.BufferedWriter name=‘<stdout>‘>
131256	 <_io.BufferedWriter name=‘<stderr>’>
73832	 {‘CRYPTOGRAPHY_PACKAGE_VERSION’: <cdata ‘char *’ 0x109f2f8bc>, ‘Cryptography_HAS_EC2M’: 1, ’Cryptogr
73832	 {‘__name__‘: ‘lib’, ‘__doc__‘: None, ‘__package__‘: None, ‘__loader__‘: None, ‘__spec__‘: None, ‘_or
73832	 {(b’\x1a\xba’, <_Address via <aiocoap.transports.simplesocketserver._DatagramServerSocketSimple obje
36976	 {4441733808: <weakref at 0x108ced770; to ‘type’ at 0x108bf7ab0 (type)>, 4441762480: <weakref at 0x10
9328	 {‘sys’: <module ‘sys’ (built-in)>, ‘builtins’: <module ‘builtins’ (built-in)>, ‘_frozen_importlib’: 
9328	 {‘__name__‘: ‘posix’, ‘__doc__‘: ’This module provides access to operating system functionality that
```

[edit: code dump formatting]

**Comment by chrysn** [comment]
Oups -- that shouldn't happen.

Thanks for spotting it and providing the test material.

 I'll look into it ASAP; the two main questions will be "where does that come from" and "why didn't the shutdown tests catch that" (as one of their purposes is to catch lingering backreferences; that this happens shows that that is insufficient to prevent memory leakage, and more tests to that are necessary).

**Comment by bzasadny** [comment]
Thanks for fast reaction:) Could you estimate when you will be have time to take a look and perform solution? Of course very roughly, it could be in one week, month or year :)

**Comment by chrysn** [comment]
Just as not to confuse this with other issues, *some* effects as you
described them are to be expected -- CoAP in general expects
deduplication to be available for up to EXCHANGE_LIFETIME (~250s), that
*is* a lot of data to store and does rise as the graph does when
incoming traffic starts. aiocoap does not (yet) implement the relaxed
duplication for idempotent messages, and does not limit that memory
either. (I've opened #183 to describe what else should be done).

So with that in mind, I tested the regression itself with a test function
like yours but limited to 10k requests fired at 0.02s intervals. (This
should take about twice the EXCHANGE_LIFETIME to run, and thus show
clearly whethere there are plateaus).

With 0.3, this initially occupies memory at a rate of 0.4MiB/s until it
statys at a 120MiB plateau after EXCHANGE_LIFETIME.
(That's kind of to be expected; at a given data rate and
EXCHANGE_LIFETIME, there is some limit to used memory; the graph not
going down after the experiment (10:21) to me looks more like Python not
freeing memory without pressure -- which is OK as it reclaims it).

With curent master (where nothing of relevance to this problem should
have changed relative to 0.4b1), the memory slope is greater at around
1.0MiB/s; the test takes 11:03 as well so data rates are comparable and
this is a significant increase in the per-package memory. Unlike in 0.3,
there is no plateau, so that's the issue I'll track in here. The data
look a bit like there is a bend at 250s in the curve (which'd indicate
that small pieces of data are dropped after EXCHANGE_LIFETIME, just not
the bulk), but I'll probably find that deeper in.

**Comment by chrysn** [comment]
Turns out that there was indeed a cleanup step missing in the token management layer. A quick test with EXCHANGE_LIFETIME=30 now shows a plateau at that time, and the slope is now much smaller again (0.2MiB per second even looks smaller than the values from the 0.3 release).

The full test shows that there is still *some* memory creep after the EXCHANGE_LIFETIME point (102MB reached after 250 seconds, creeping up to 117 after 500), but it's stable over there.

![after-first-fix](https://user-images.githubusercontent.com/442326/74148305-71710080-4c05-11ea-94ba-66f2672ddc6f.png)

I'll leave this open as I'd like to hunt down the remaining "creep", but the larger issue should be done with.

Could you verify that latest master solves the problem as you have it?

**Comment by chrysn** [comment]
For sake of completeness, I've observed the server a bit longer after the first test completed, and memory *does* eventually start dropping back. This shows a second test run started right when the first memory drop was intercepted; the new messages fill up the not-yet-freed memory up to the point where some is required again, and (in this example, possibly due to other processes slowing the data exchange) didn't even reach the original peak. The memory drop at the end happened when memory pressure was applied to the system, and it went back a bit when processing messages again -- just to illustrate which effects come into play in these diagrams.
![longtermserver](https://user-images.githubusercontent.com/442326/74150758-e266e700-4c0a-11ea-8c22-906cb7cbc10f.png)

**Comment by bzasadny** [comment]
Good job! Thanks a lot!:)
