### ISSUE TITLE
bind(address, 0) doesn't bind to a random port

### ISSUE THREAD

**Issue by aellwein** [chrysn/aiocoap#194]
While testing the aellwein/lwm2mclient#11 on Mac i've detected another weird behaviour. This line of code

```        
self.context = await Context.create_server_context(self, bind=(self.address, 0))
```

is used to create a server on a given interface and a _random_ port, it worked  in previous versions of aiocoap
ever since, but somehow the semantic is changed to
```
bind = (bind[0], bind[1] or COAP_PORT)
```
(found at least in simplesocket.py, udp6.py)

which lets the LwM2M client's server to bind on port 5683 by default. 
However, in my expectation, the bind() should use a random port if zero is provided.

Hint: a LwM2M client needs to have a CoAP server on some port (in this context, other than 5683, otherwise
we have a conflict with the local Leshan server).

P.S. In my opinion, this behaviour is not MacOS specific.

```
python3 -m aiocoap.cli.defaults

Python version: 3.8.3 (default, May 27 2020, 20:54:22) 
[Clang 11.0.3 (clang-1103.0.32.59)]
aiocoap version: 0.4b3
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: everything there
    linkheader: everything there
    prettyprint: missing termcolor, pygments
Python platform: darwin
Default server transports:  oscore:tcpserver:tcpclient:tlsserver:tlsclient:simple6:simplesocketserver
Selected server transports: oscore:tcpserver:tcpclient:tlsserver:tlsclient:simple6:simplesocketserver
Default client transports:  oscore:tcpclient:tlsclient:simple6
Selected client transports: oscore:tcpclient:tlsclient:simple6
SO_REUSEPORT available (default, selected): True, True
```

**Comment by chrysn** [comment]
Thanks, that does look like a regression; fix incoming (that distinguishes between 0 = "yes I really mean 0, pass this on to the OS to do the right thing" and the default None = "just pick the default port for each protocol").

For the particular application (LwM2M), I think that using the simple6 transport with a server is more suitable -- not so much for the benefit of accepting messages only from the LwM2M server, but because this creates a bound socket that can receive ICMP errors.
