### ISSUE TITLE
Websocket transport layer, remote usage

### ISSUE THREAD

**Issue by gilloud** [chrysn/aiocoap#214]
Hi all,
Thanks a lot for this incredible work. I’m currently working to be able to have a bi-directional CoAP layer between a client and a server. And, after a successful work with UDP protocol, I have issues with the websocket layer (on master branch)

My connection is successfully opened from my client, to my server, but I have doubts about the capacity to the server to send a request to the client thru the opened tunnel.

When the request come to the `fill_or_recognize_remote` the first condition
https://github.com/chrysn/aiocoap/blob/master/aiocoap/transports/ws.py#L273 the “message.remote._pool() is never self” and a reconnect is always requested

Have you an idea about the cause of this errors ?

**Comment by chrysn** [comment]
The client in a CoAP-over-WS has no meaningful URI. That's a concept not really expressed in the RFCs, but think of the address on the client like `coap+ws://💻➀➃➂➆/some/path` -- even if you could write it down, nobody else could can make sense of it (and thus aiocoap doesn't even try).

Rather than how you'd normally phrase requests by creating a `Message(uri="coap://device/some/path", accept=...)`, you'll need to explicitly set the messages `.remote` property to the very `.remote` that you got when the client connected. You can set the path either by setting `uri="coap://doesntreallymatter/some/path"` and later override the `.remote`, or you just set `uri_path=["some", "path"]` and don't work in URI space at all -- as long as you later set a `.remote`. An example of how this is done is [in the Resource Directory](https://github.com/chrysn/aiocoap/blob/103518d157e854a72933c9cb0c525d86c70d3327/aiocoap/cli/rd.py#L559) -- when a request gets in in a to-be-proxied connection, it takes a different path compared to the regular one where a full base URI is present.

**Comment by chrysn** [comment]
Closing this as it is hopefully answered sufficiently; please reopen if I misunderstood the question or the answer is incomplete.
