### ISSUE TITLE
Failure if ipv6 is not enabled

### ISSUE THREAD

**Issue by zeridon** [chrysn/aiocoap#222]
While working with homeassistant which uses aiocoap (in relation to the shelly integration) the following error is observed:

```

Logger: homeassistant.setup
Source: components/shelly/__init__.py:30
First occurred: 3:10:31 PM (1 occurrences)
Last logged: 3:10:31 PM
Error during setup of component shelly

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 30, in async_setup
    hass.data[DOMAIN][COAP_CONTEXT] = await aiocoap.Context.create_client_context()
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 179, in create_client_context
    await self._append_tokenmanaged_messagemanaged_transport(
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 147, in _append_tokenmanaged_messagemanaged_transport
    transport = await message_interface_constructor(mman)
  File "/usr/local/lib/python3.8/site-packages/aiocoap/transports/udp6.py", line 237, in create_client_transport_endpoint
    sock = socket.socket(family=socket.AF_INET6, type=socket.SOCK_DGRAM)
  File "/usr/local/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

```

This Boils down to:
```
  File "/usr/local/lib/python3.8/site-packages/aiocoap/transports/udp6.py", line 237, in create_client_transport_endpoint
    sock = socket.socket(family=socket.AF_INET6, type=socket.SOCK_DGRAM)
  File "/usr/local/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

Which in itself is directly related to the fact i do not have `IPv6` enabled on the machine i am getting this. Similar error is not observed on the other transports (e.g. https://github.com/chrysn/aiocoap/blob/master/aiocoap/transports/tcp.py).

Please provide ways for this to run without IPv6 being available. https://stackoverflow.com/a/4307289 offers a simple looking solution.

BR

**Comment by chrysn** [comment]
IPv6 is *the* way applications can talk to the network stack in a
standardized way. While most features of the v6 socket API are present
in the v4 API as well, they pose way harder interoperability problems.
(For example, in6_pktinfo is specified in RFC3542, whereas the v4
equivalent is more platform dependent). As IPv6 is supported by any
reasonably modern operating system, there is no reason to not assume the
stack is there.

Systems where v6 is turned off usually have that off due to some
misconfiguration, either on the part of the host operator or the network
provider; please consider fixing those at the root.

I may be able to help with some of the simpler causes in this thread
(can't make any promises, but it doesn't hurt to write here why you
turned it off in the first place), but aiocoap is not ever expected to
work on a system where IPv6 is turned off. It may happen to work when
using the more limited transports, but they are disabled by default for
good reasons (namely the lack of good support for role reversal, and the
limited error handling).

**Comment by zeridon** [comment]
Thanks for your comment. First let me note that i am in no way familiar how exactly is CoAP supposed to work. After that being out here are my reasons for explicitly disabling IPv6:

 * Improved security - services that listen on *:<port> do listen on v6 and that is not something that i want
 * One less firewall ruleset to configure
 * My network is small and does not benefit from IPv6
 * No RA/ND services need to be configured, maintained and secured

**Comment by chrysn** [comment]
On how CoAP is supposed to work: well, mainly over IPv6 ;-)

Just kidding: It *does* have provisions in place for IPv4, and works well there. You should, however, expect that when you use more of CoAP, eventually you'll run into devices that don't have a v4 stack at all, eg. because of its increased complexity (no guaranteed MTU) or because there is no IPv4 transport for their medium, eg. low-power devices based on IP-over-802.15.4 (which is what Zigbee uses).

On the practical side, if you already configure a firewall: You can still drop all v6 traffic there. That should be just as much a single line of configuration as disabling IPv6. Not that I'd particularly recommend it, but as long as not having v6 at all works for you, it should have the same effect but not get in the way of applications that depend on the operating system's IPv6 APIs even for their v4 traffic.

**Comment by zeridon** [comment]
thanks for the comment ;)

**Comment by chrysn** [comment]
Does blocking v6 rather than disabling it on the OS level solve the issue for your setup?

I'd like to add a section to the FAQ on that, but need a bit of feedback of whether the proposed solutions work for those affected.

**Comment by zeridon** [comment]
Unfortunately i am not using CoAP. Will setup a testbed when i am at home and can play with it and report back.

Do remind me if i don't post anything in the next week or so. :)

**Comment by zeridon** [comment]
Firewalling ipv6 does not render the original error. So yes can be used as a security feature.
