### ISSUE TITLE
aiocoap-rd resource registration error

### ISSUE THREAD

**Issue by Ramzi04** [chrysn/aiocoap#243]
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
aiocoap version: 0.4.1
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: everything there
    linkheader: everything there
    prettyprint: everything there
Python platform: linux
Default server transports:  oscore:tcpserver:tcpclient:tlsserver:tlsclient:ws:udp6
Selected server transports: oscore:tcpserver:tcpclient:tlsserver:tlsclient:ws:udp6
Default client transports:  oscore:tcpclient:tlsclient:ws:udp6
Selected client transports: oscore:tcpclient:tlsclient:ws:udp6
SO_REUSEPORT available (default, selected): True, True

1- I run RD :  `python3 aiocoap-rd`
2- I register a EP : `aiocoap-client --method POST --content-format 40 --payload '' coap://localhost/resourcedirectory/?ep=node1`
3- I tried to register a resource : `aiocoap-client --method POST --content-format 40 --payload '</sensors/temp>;rt="temperature-c";secure=1' coap://localhost/resourcedirectory/?ep=node1`
Then i got this error in aiocoap-rd:
`ERROR:coap-server:An exception occurred while rendering a resource: KeyError(None)
Traceback (most recent call last):
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/protocol.py", line 383, in _render_to_plumbing_request
    await self._render_to_plumbing_request_inner(plumbing_request,
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/protocol.py", line 512, in _render_to_plumbing_request_inner
    response = await self.serversite.render(request)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 694, in render
    return await Site.render(self, request)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/resource.py", line 369, in render
    return await child.render(subrequest)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/resource.py", line 117, in render
    response = await m(request)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 391, in render_post
    regresource = self.common_rd.initialize_endpoint(request.remote, registration_parameters)
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 319, in initialize_endpoint
    oldreg.delete()
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 208, in delete
    self._delete_cb()
  File "/home/aiocoap/master/thesis/aiocoap/aiocoap/cli/rd.py", line 330, in delete
    self.proxy_active.pop(proxy_host)
KeyError: None
`

**Comment by Ramzi04** [comment]
I forget to tell you that when I run step 3 the second time, it registers **successfully** the resource </sensors/temp>.

**Comment by chrysn** [comment]
> 2- I register a EP : `aiocoap-client --method POST --content-format 40 --payload '' coap://localhost/resourcedirectory/?ep=node1`
> 3- I tried to register a resource : `aiocoap-client --method POST --content-format 40 --payload '</sensors/temp>;rt="temperature-c";secure=1' coap://localhost/resourcedirectory/?ep=node1`

Just to clarify for others following this issue (and you to confirm that
this is the intention):

In step 2, you register with an empty set of links. In 3, you register
again with a set of links now containing one link. That should (but, and
that's aiocoap-rd's error, doesn't) replace the old registration with a
new one that.

In an even more minimal example, the third step could also be

```
$ aiocoap coap://localhost/reg/1/ --method DELETE
```

raising the same error.


The error occurred because the deletion process tried to delete the
associated proxy service too (which does not, in all conditions, exist);
now (well, once tests ran through here and I've pushed, shouldn't take
more than a few minutes) it accepts absence of such a service, and
deletion (and recreation) can pass through right away.

-- 
To use raw power is to make yourself infinitely vulnerable to greater powers.
  -- Bene Gesserit axiom

**Comment by chrysn** [comment]
Closed in 807beaf20931c372ae133a1f8758e251f545c2c1 (after I have, once again, forgotten to put the "Closes:" line in the commit).

**Comment by Ramzi04** [comment]
Actually, in the step 2, I want to register only the endpoint ep=node1. In step 3, I want to attach some resources (web links) to the registered endpoint.
