### ISSUE TITLE
Resource changed when Etag is not in block2 response

### ISSUE THREAD

**Issue by rxk08011** [chrysn/aiocoap#246]
There is one CoAP server running on Embedded device and we call API from aiocoap client. Response size is 7107 bytes.

Aiocoap client rejects response because Etag and block size is not part of further responses after first initial confirmation response. Due to this we receive an error Resource changed.

I have attached Wireshark capture where you can see the problem. First successful response
 is for other client which works perfectly.

[coap_requests.zip](https://github.com/chrysn/aiocoap/files/6876599/coap_requests.zip)

**Comment by chrysn** [comment]
I think that this is the expected behavior, at least when it comes to
ETag; quoting RFC7959: "If an ETag Option is available, the client, when
reassembling the representation from the blocks being exchanged, MUST
compare ETag Options.", and later "the server SHOULD include an ETag
Option in each response, and the reassembling client MUST compare the
ETag Options".

As the ETag is set on the first block, the checking behavior is triggered.

Can you fix the server to produce the option? As long as the option is
not sent in all blocks, the client can not notice when the resource
changes on the server side, would assemble JSON that may or may not be
valid, and cause all sorts of spurious crashes in the application later
on.

(As for the Size2, I'm not sure whether the client will act correctly,
but this is most easily tested once the ETag part is sorted out).
