### ISSUE TITLE
Using CBOR as a request payload format

### ISSUE THREAD

**Issue by Ramzi04** [chrysn/aiocoap#257]
Hi @chrysn.

I want to send a request using CBOR instead of JSON in order to reduce the request size.

```
json_var = '{"L1":"if=core.a&lt=12000"}
requestJSON = Message(content_format=50,code=FETCH, payload=payload, uri='coap://localhost/resource-lookup/')
requestCBOR = Message(content_format=60,code=FETCH, payload=payload, uri='coap://localhost/resource-lookup/')
print('Request FETCH size in Bytes: %r'%(  len(requestJSON.encode()))) 
print('Request FETCH size in Bytes: %r'%(  len(requestCBOR.encode()))) 
```

How to convert json_var to CBOR in order to **reduce the request size** ? 
and it is correct how the request size is calculated ?

**Comment by chrysn** [comment]
This is unrelated to aiocoap -- you can use the `cbor2` module that aiocoap also uses, but given you're passing in the JSON in pre-encoded form (which, by the way, wont' work as used here because it's a string and not bytes; `b"{...}"` should do the trick), you'll need to decode it beforehand and than pass it through cbor2.
