### ISSUE TITLE
How to send file with PUT method to a server using block1 (block wise transfert)

### ISSUE THREAD

**Issue by moonlight83340** [chrysn/aiocoap#359]
I have tried to develop a python client able to transfert file with coap PUT and block1. But I guess I missunderstand something and I'm not able to do that.

I have done something like that : 

```python
    protocol = await aiocoap.Context.create_client_context()
    uri = f'coap://{ip_addr}{uri}'
    
    block_size_exponent = get_block_size_exponent(block_size)
    
    # Fragment the payload into blocks
    blocks = [payload[i:i + block_size] for i in range(0, len(payload), block_size)]
    block_num = 0
    print("len(blocks) : ",len(blocks))
    for block in blocks:
        more = True if block_num < len(blocks) - 1 else False
        request = aiocoap.Message(code=aiocoap.PUT, uri=uri, payload=block)
        request.opt.content_format = aiocoap.numbers.ContentFormat.OCTETSTREAM
        request.opt.block1 = aiocoap.optiontypes.BlockOption.BlockwiseTuple(block_num, more, block_size_exponent)
        print("block_num : ",request.opt.block1.block_number)
        print("more : ",request.opt.block1.more)
        print("block_size_exponent : ",request.opt.block1.size_exponent)
        
        try:
            response = await protocol.request(request).response
            if response.code.is_successful():
                print(f"\033[32m[OK] Block {block_num}\033[0m")
                block_num += 1
            else:
                print(f"\033[31mFailed at block {block_num}: {response.code}\033[0m")
                return False
        except Exception as e:
            print(f"\033[31mFailed. Abort test: {e}\033[0m")
            return False
```

Server seems to wait for a block1 request.
I'm new to aiocoap (less than a week) so if you have any tips I could take 😄 

[edit: changed markdown to use python syntax highlighting --chrysn]

**Comment by moonlight83340** [comment]
With this code I get an error, "Unexpected more-flag in app request".

**Comment by chrysn** [comment]
Is there any good reason to not just let aiocoap do the block-wise handling?

**Comment by moonlight83340** [comment]
> Is there any good reason to not just let aiocoap do the block-wise handling?

Thank for your reply ! I would like to be able to simulate packet loss in fact 😅 but maybe it's not a good idea like that.. and i would like to choose the blocksize sent 😅

**Comment by chrysn** [comment]
For packet loss simulation, doing block-wise manually won't help – this is better done [at the OS level](https://stackoverflow.com/questions/614795/simulate-delayed-and-dropped-packets-on-linux). If for some reason this is unusable, I think you'd be better off modifying the CoAP transport (typically aiocoap/transports/udp6.py) to not send some packets.

As for the block size, you can still send the whole request as a whole, but you can alter the maximum_remote_size_exp. Due to a bug I just found reviewing this, you can not yet use

```python
request = aiocoap.Message(code=aiocoap.PUT, uri=uri, payload=everything)
request.remote.maximum_block_size_exp = 4
```

*yet*, but you can override this globally by setting

```python
aiocoap.transports.udp6.UDP6EndpointAddress.maximum_block_size_exp = 4
```

instead.

(There is an older way of sending the request with the full payload but a request.opt.block1 that just has the block size and no more bit, but that is deprecated already in favor of the yet-to-be-finished per-remote hints).

**Comment by moonlight83340** [comment]
Thank you for your answer, it helped a lot ! 😄
