### ISSUE TITLE
Protocol socket closed behaviour

### ISSUE THREAD

**Issue by lwis** [chrysn/aiocoap#79]
Hi,

After some testing for ggravlingen/pytradfri#37 on the tinydtls branch of aiocoap, I've been a little confused by some behaviour and would appreciate some advice, or clarification on how the protocol is expected to behave.

I'm caching the client protocol between requests, which allows for better performance and more concurrent resource observations. However, if I unplug my gateway (the source) the protocol does not react, all future requests timeout, but the observations continue without any new messages. In my implementation the only way the observations will be reset is if a new request is made which highlights the issue with the current protocol.

Now, I'm not sure if coap supports it, or if there's a more effective way of monitoring the state of the socket - but is a heartbeat something to consider to avoid having to reset the client protocol manually?

**Comment by chrysn** [comment]
> I'm caching the client protocol between requests, which allows for
> better performance and more concurrent resource observations.

This is the intended mode of operation; there are very few reasons why
an application should have more than one protocol. Do you think the
documentation or examples indicate otherwise? If so, I'll try to clarify
this.

> However, if I unplug my gateway (the source) the protocol does not
> react,

This is by design in CoAP. What can be done on the protocol side (but is
not supported by aiocoap yet) is renewal of observations -- basically
the client asking for confirmation on the observation still being up.

I'll look into how this is best added (apart from fixing the crashes
that happen when a DTLS request fails -- the dtls branch *is* still
experimental), but I'm not sure yet when I can get to it.

**Comment by lwis** [comment]
@chrysn makes sense, that's fine. Will see what I can do as a workaround/potentially contributing. :+1: Thanks!
